--- ./makefile	2019-11-14 16:00:53.313285514 +0000
+++ ./makefile	2019-11-14 15:45:28.148939006 +0000
@@ -2,32 +2,28 @@
 
 GITCOUNT        = $(shell git rev-list HEAD --count)
 UNAME           = $(shell uname)
-CFLAGS          = -Wall -g -O -Ihidapi/hidapi -DGITCOUNT='"$(GITCOUNT)"'
+CFLAGS          = -Wall -g -O -DGITCOUNT='"$(GITCOUNT)"'
 LDFLAGS         = -g
 CCARCH          =
 
 # Linux
 ifeq ($(UNAME),Linux)
     LIBS        += -Wl,-Bstatic -lusb-1.0 -Wl,-Bdynamic -lpthread -ludev
-    HIDLIB      = hidapi/libusb/.libs/libhidapi-libusb.a
 endif
 
 # FreeBSD
 ifeq ($(UNAME),FreeBSD)
     LIBS        += -liconv -lusb -lpthread
-    HIDLIB      = hidapi/libusb/.libs/libhidapi.a
 endif
 
 # DragonFly BSD
 ifeq ($(UNAME),DragonFly)
     LIBS        += -Wl,-Bstatic -lusb -Wl,-Bdynamic -lpthread
-    HIDLIB      = hidapi/libusb/.libs/libhidapi.a
 endif
 
 # Mac OS X
 ifeq ($(UNAME),Darwin)
     LIBS        += -framework IOKit -framework CoreFoundation
-    HIDLIB      = hidapi/mac/.libs/libhidapi.a
     UNIV_ARCHS  = $(shell grep '^universal_archs' /opt/local/etc/macports/macports.conf)
     ifneq ($(findstring i386,$(UNIV_ARCHS)),)
         CCARCH  += -arch i386
@@ -39,10 +35,9 @@
 endif
 
 PROG_OBJS       = pic32prog.o target.o executive.o serial.o \
-                  adapter-pickit2.o adapter-hidboot.o adapter-an1388.o \
-                  adapter-bitbang.o adapter-stk500v2.o adapter-uhb.o \
-                  adapter-an1388-uart.o configure.o \
-                  family-mx1.o family-mx3.o family-mz.o family-mm.o $(HIDLIB)
+                  adapter-bitbang.o adapter-stk500v2.o \
+		  configure.o \
+                  family-mx1.o family-mx3.o family-mz.o family-mm.o
 
 # JTAG adapters based on FT2232 chip
 CFLAGS          += -DUSE_MPSSE
@@ -75,32 +70,17 @@
 		cp pic32prog-ru-cp866.mo ru/LC_MESSAGES/pic32prog.mo
 
 clean:
-		rm -f *~ *.o core pic32prog adapter-mpsse pic32prog.po hidapi/ar-lib hidapi/compile
-		if [ -f hidapi/Makefile ]; then make -C hidapi clean; fi
+		rm -f *~ *.o core pic32prog adapter-mpsse pic32prog.po 
 
 install:	pic32prog #pic32prog-ru.mo
 		install -c -s pic32prog /usr/local/bin/pic32prog
 #		install -c -m 444 pic32prog-ru.mo /usr/local/share/locale/ru/LC_MESSAGES/pic32prog.mo
 
-hidapi/hidapi/hidapi.h:
-		git submodule update --init
-
-$(HIDLIB):      hidapi/hidapi/hidapi.h
-		if [ ! -f hidapi/configure ]; then cd hidapi && ./bootstrap; fi
-		cd hidapi && ./configure --enable-shared=no CFLAGS='$(CCARCH)'
-		make -C hidapi
-
 ###
-adapter-an1388-uart.o: adapter-an1388-uart.c adapter.h pic32.h serial.h
-adapter-an1388.o: adapter-an1388.c adapter.h hidapi/hidapi/hidapi.h pic32.h
 adapter-bitbang.o: adapter-bitbang.c adapter.h pic32.h serial.h \
   bitbang/ICSP_v1E.inc
-adapter-hidboot.o: adapter-hidboot.c adapter.h hidapi/hidapi/hidapi.h pic32.h
 adapter-mpsse.o: adapter-mpsse.c adapter.h pic32.h
-adapter-pickit2.o: adapter-pickit2.c adapter.h hidapi/hidapi/hidapi.h pickit2.h \
-  pic32.h
 adapter-stk500v2.o: adapter-stk500v2.c adapter.h pic32.h serial.h
-adapter-uhb.o: adapter-uhb.c adapter.h hidapi/hidapi/hidapi.h pic32.h
 configure.o: configure.c target.h adapter.h
 executive.o: executive.c pic32.h
 family-mx1.o: family-mx1.c pic32.h
